### ISSUE TITLE
Demo

### ISSUE THREAD

**Issue by dohliam** [milouse/centigram#1]
This is great! As a heavy user of milligram I've been looking for a drop-in replacement that has support for preferred (light/dark) colour schemes, and this looks amazing.

I've just added centigram to the collection at [dropin-minimal-css)](https://github.com/dohliam/dropin-minimal-css) since I think it fills an important niche, particularly since milligram seems to be on hiatus.

I notice that there doesn't seem to be a demo yet, so in case it's useful people interested in using centigram can check out the preview [here](https://dohliam.github.io/dropin-minimal-css/?centigram) which basically just overlays the CSS on top of some HTML5 boilerplate.

**Comment by milouse** [comment]
Hi, and sorry for the long silence. Somehow I didn’t receive notifications on my repo and missed your issue.

Thank you very much to add this little thing into your list.

In any case I added a demo myself in the mean time under this URL: https://milouse.github.io/centigram/demo.html
