### ISSUE TITLE
Unminified CSS

### ISSUE THREAD

**Issue by dohliam** [milouse/centigram#2]
One small request -- would it be possible to include an unminified source file for centigram in the `dist` directory? For example, milligram offers [both `milligram.css` and `milligram.min.css`](https://github.com/milligram/milligram/tree/main/dist) files. This would make it a bit easier to track changes between versions, among other things. Thanks again for this nice fork!

**Comment by diomed** [comment]
this is reasonable suggestion. 
I agree with it.

there are , btw tools online that can unminify code.
you can use unminify.com for example, to get it in your repo unminified,
if you wish.

**Comment by milouse** [comment]
Hi, and sorry for the long silence, I did not receive the repository notification until today 🤦

This is indeed a good suggestion and I already fix the build workflow to also keep the unminified file in the dist folder.

**Comment by dohliam** [comment]
Thanks @milouse! I have now updated the URL for Centigram so the latest version will be used from now on.
